@startuml 

skinparam classAttributeIconSize 0
skinparam linetype polyline

abstract class Component {
+ ComputeComponentDuration()
}

class Project extends Component {
+ ComputeComponentDuration()
}


class Task extends Component {
+ ComputeComponentDuration()
}

class Intervals {
}

Interface Observer{
}

abstract class Observable {
}

class Clock {
- uniqueInstance
- Clock()
+ getInstance()
}

class Client{
+ Main()
}

class DataManager{  
+ SaveUserData()
- LoadUserData()
+ ComponentTotalDuration()
}

Class Printer{
}

DataManager -down-> "*" Component: Contains
Project --> "*" Component
Client -left-> DataManager
Task -left-> "*" Intervals:Contains
Clock .down.> Observable
Observable -Down-> "*" Observer
Intervals -left-> Observer
DataManager -left-> Printer
Task -[hidden]right-> Project

@enduml